// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5K4xx7wFXFBMQi15CenqTfwQswh_53g',
    appId: '1:687699391365:web:5dcb02e579d8a86665caec',
    messagingSenderId: '687699391365',
    projectId: 'ecomfaza1',
    authDomain: 'ecomfaza1.firebaseapp.com',
    storageBucket: 'ecomfaza1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ykLMMAI9HTGy6yby7sJ2Pfc6vn3G1gk',
    appId: '1:687699391365:android:20c9dcff63b46bae65caec',
    messagingSenderId: '687699391365',
    projectId: 'ecomfaza1',
    storageBucket: 'ecomfaza1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhb_XSeb7U6viMx3LU-Ftv9h63oJTUifs',
    appId: '1:687699391365:ios:2efe6be782733e0465caec',
    messagingSenderId: '687699391365',
    projectId: 'ecomfaza1',
    storageBucket: 'ecomfaza1.appspot.com',
    iosClientId: '687699391365-mbqqml5uvdm3bdjpbci2ur9eh2dl94qp.apps.googleusercontent.com',
    iosBundleId: 'com.sinasys.eCommerceFlutter',
  );
}
